[package]
name = "cargo-mpirun"
version = "0.1.0"
authors = ["Andrew Gaspar <andrew.gaspar@outlook.com>"]

[dependencies]
clap = { version = "~2.29", features=["yaml"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"